// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzuxqgnackvqwyvrymtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dXhxZ25hY2t2cXd5dnJ5bXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzA5OTksImV4cCI6MjA2OTY0Njk5OX0.wIyF9Nb3veQepYcpXxgkNHMctOlu6yLZld5nGL94l80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});